e4e= '/Ext_4T_SSD/ASHOK/DragVideo/DragGAN/_PTI/pretrained_models/e4e_ffhq_encode.pt'
stylegan2_ada_ffhq= '/Ext_4T_SSD/ASHOK/DragVideo/DragGAN/_PTI/pretrained_models/ffhq.pkl'
checkpoints_dir= '/Ext_4T_SSD/ASHOK/DragVideo/Data_store/experiments/exp_01_pti_1_inv_1/tuned_SG'
embedding_base_dir= '/Ext_4T_SSD/ASHOK/DragVideo/Data_store/experiments/exp_01_pti_1_inv_1/latents'
input_data_path= '/Ext_4T_SSD/ASHOK/DragVideo/Data_store/experiments/exp_01_pti_1_inv_1/aligned'
