e4e= '/home/bean/DragVideo/DragGAN/_PTI/pretrained_models/e4e_ffhq_encode.pt'
stylegan2_ada_ffhq= '/home/bean/DragVideo/DragGAN/_PTI/pretrained_models/ffhq.pkl'
checkpoints_dir= '/home/bean/DragVideo/Data_store/experiments/2023-09-01_01-35-09_vsauce_ffmpeg/tuned_SG'
embedding_base_dir= '/home/bean/DragVideo/Data_store/experiments/2023-09-01_01-35-09_vsauce_ffmpeg/latents'
input_data_path= '/home/bean/DragVideo/Data_store/experiments/2023-09-01_01-35-09_vsauce_ffmpeg/aligned'
quad_values_path= '/home/bean/DragVideo/Data_store/experiments/2023-09-01_01-35-09_vsauce_ffmpeg/quad_values'
